# Generated by Django 4.1.7 on 2023-03-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('idtemas', models.IntegerField(db_column='idTemas', primary_key=True, serialize=False)),
                ('nome_tema', models.CharField(max_length=45)),
                ('foto_tema', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idpost', models.OneToOneField(db_column='idpost', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='blogapp.temas')),
                ('nome_post', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
